import type { Metadata } from "next";
import { AppProps } from "next/app";
import { Ubuntu_Mono, Cutive_Mono } from "next/font/google";
import "../styles/globals.scss";
import { c } from "../utils";
import Navbar from "@/components/Navbar";

const ubuntuMono = Ubuntu_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ubuntu-mono",
});
const cutiveMono = Cutive_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cutive-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Navbar className={c(ubuntuMono.variable, cutiveMono.variable)} />
      <main className={c(ubuntuMono.variable, cutiveMono.variable)}>
        <Component {...pageProps} />
      </main>
    </>
  );
}

export default MyApp;
